//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmDisplay.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAlarm", CallbackContract=typeof(AlarmDisplay.ServiceReference1.IAlarmCallback))]
    public interface IAlarm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarm/alarmInit", ReplyAction="http://tempuri.org/IAlarm/alarmInitResponse")]
        void alarmInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarm/alarmInit", ReplyAction="http://tempuri.org/IAlarm/alarmInitResponse")]
        System.Threading.Tasks.Task alarmInitAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarm/onAlarmActivated", ReplyAction="http://tempuri.org/IAlarm/onAlarmActivatedResponse")]
        void onAlarmActivated(Model.Alarm a, double value, System.DateTime time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmChannel : AlarmDisplay.ServiceReference1.IAlarm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmClient : System.ServiceModel.DuplexClientBase<AlarmDisplay.ServiceReference1.IAlarm>, AlarmDisplay.ServiceReference1.IAlarm {
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void alarmInit() {
            base.Channel.alarmInit();
        }
        
        public System.Threading.Tasks.Task alarmInitAsync() {
            return base.Channel.alarmInitAsync();
        }
    }
}
