//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trending.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITrending", CallbackContract=typeof(Trending.ServiceReference1.ITrendingCallback))]
    public interface ITrending {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/trendingInit", ReplyAction="http://tempuri.org/ITrending/trendingInitResponse")]
        void trendingInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/trendingInit", ReplyAction="http://tempuri.org/ITrending/trendingInitResponse")]
        System.Threading.Tasks.Task trendingInitAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/onValueRead", ReplyAction="http://tempuri.org/ITrending/onValueReadResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.InputTag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.DigitalInput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.AnalogInput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.OutputTag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.DigitalOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.AnalogOutput))]
        void onValueRead(Model.Tag t, double value, System.DateTime time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingChannel : Trending.ServiceReference1.ITrending, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingClient : System.ServiceModel.DuplexClientBase<Trending.ServiceReference1.ITrending>, Trending.ServiceReference1.ITrending {
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void trendingInit() {
            base.Channel.trendingInit();
        }
        
        public System.Threading.Tasks.Task trendingInitAsync() {
            return base.Channel.trendingInitAsync();
        }
    }
}
